accounts/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

#from accounts.views import AccountActivationView as ActivationView
from accounts.views import AccountRegistrationView as RegistrationView
from accounts.views import AccountEditView
from registration.backends.default.views import ActivationView

urlpatterns = patterns('',
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
					   
					   
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           ActivationView.as_view(),
                           name='registration_activate'),
					   
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
					   url(r'^register/X/$',
                           AccountEditView.as_view(template_name='registration/registration_form.html'),
                           name='registration_disallowed'),
                       )
					   
                       

pybbm_sample/urls.py
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pybbm_sample.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^forum/',include('pybbm_tag.urls', namespace='pybb_tag')),
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^dashboard/', 'portal.views.dashboard'),
	url(r'^home/(?P<insti>[a-z]+)/dashboard', 'portal.views.homepage_admin'),
	url(r'^home/(?P<insti>[a-z]+)/', 'portal.views.homepage'),	
    url(r'^$', 'portal.views.index'),
	url(r'^events/(?P<event_id>\d+)/','portal.views.events'),
    url(r'^dajaxice/',include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

)

urlpatterns += patterns('django.views.static', (r'^static/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.STATIC_ROOT,
                        'show_indexes': True}))

portal/models.py
from django.db import models
from accounts.models import UserData,institutes

class Event(models.Model):
	name = models.CharField(max_length=30)
	description = models.TextField(max_length=100)
	date_time = models.DateTimeField('Date, time')
	location = models.CharField(max_length=40)
	users = models.ManyToManyField(UserData)
	
	def __unicode__(self):
		return self.name
	

class Update(models.Model):
	title = models.CharField(max_length=30)
	date_time = models.DateTimeField('Date, time')
	update = models.TextField(max_length=50)
	
	def __unicode__(self):
		return self.title
		
class Homepage(models.Model):
	institute = models.CharField(choices = institutes, max_length=50)
	description = models.TextField(max_length=200)
	image = models.ImageField(upload_to='media/homepages/')
	
	def __unicode__(self):
		return self.institute

portal/forms.py
from django import forms
from portal.models import *
from django.contrib.admin import widgets

class AddEventForm(forms.ModelForm):
	#name = forms.CharField(max_length=30)
	#description = forms.CharField(max_length=60,widget=forms.Textarea)
	#date_time = forms.DateTimeField('date_time')
	#location = forms.CharField(max_length=40)
	
	class Meta:
		model = Event
		exclude = ('users', )

class AddUpdateForm(forms.ModelForm):
	
	class Meta:
		model = Update
		
class HomepageForm(forms.ModelForm):
	
	class Meta:
		model = Homepage

portal/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect, HttpResponse
from portal.models import *
from django.template import RequestContext
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from portal.forms import *

@staff_member_required	
def dashboard(request):
	events = Event.objects.all()
	updates = Update.objects.all()
	form_add_event = AddEventForm()
	form_add_update = AddUpdateForm()
	rc = RequestContext(request,{'events':events, 'updates':updates,'add_event_form':form_add_event,'add_update_form':form_add_update})
	return render_to_response('portal/dashboard.html', rc)

def index(request):
	# assert False
	if request.user.is_staff:
		return dashboard(request)
	else:
		return render_to_response('home.html', locals(), context_instance = RequestContext(request))

def events(request, event_id):
	even = Event.objects.get(id = event_id)
	all_users = even.users.all()
	if request.user.is_authenticated():
		user = request.user	
		data = UserData.objects.get(user = user)
		if data in even.users.all():
			joined = 1
		else:
			joined = 0
		num = len(all_users) - joined	
		rc = {'event':even, 'user':user, 'joined':joined, 'num':num}
	else:
		num = len(all_users)
		joined = 0
		rc = {'event':even, 'joined':joined, 'num':num,}
	return render_to_response('portal/event.html', rc)

def homepage(request, insti):
	insti = insti.capitalize()
	homepage = Homepage.objects.get(institute = insti)
	cont = {'homepage':homepage}
	return render_to_response('portal/homepage.html', cont)
	
def homepage_admin(request, insti):
	if request.user.username != insti+'_admin' and not request.user.is_superuser:
		return HttpResponseRedirect('/home/'+insti)
	insti = insti.capitalize()
	homepage = Homepage.objects.get(institute = insti)
	cont = {'homepage':homepage}
	return render_to_response('portal/homepage_admin.html',cont)

templates/portal/add_event.html
{% load staticfiles %}	

<table>	
	<form id='f1' class="form form-horizontal">
	{% csrf_token %}
		    {{ add_event_form.as_table }}
			<tr>
				<th>Send notification mail to:</th>
				<td>
				<div id='select2_container_1' style='width:200px'>
				<select multiple id="insti" name="insti" style='width:250px'>
					<option>All</option>
					{% for iit in mail_list %}
					<option value="{{ iit }}">{{iit}}</option>
					{% endfor %}
				</select>
				</div>
				</td>
			</tr>
			<tr>
			<td></td>
			<td>
			<div id='select2_container_2' style='width:200px'>
				<select multiple id="type" name="type" style='width:250px'>
					<option>All</option>
					<option>General</option>
					<option>Current Student/Faculty</option>
					<option>Alumnus</option>
					<option>Verified Alumnus</option>
				</select>
			</div>
			</td>
			</tr>
			<tr>
			<th></th>
			<td>
				<a class='btn btn-primary btn-xs' onclick="if(change_input()) Dajaxice.portal.save_event(Dajax.process, {'form':$('#f1').serialize(true),'insti':$('#insti').val(),'type':$('#type').val(),})" >Save</a>
				<a onclick='cancel()' class='btn btn-danger btn-xs'>Cancel</a>
			</td>
			</tr>
	</form>
</table>

templates/portal/add_update.html
{% load staticfiles %}	

	<form id='f1' method=post >
	{% csrf_token %}
		<table>
		    {{ add_update_form.as_table }}				
		<tr>
			<th></th>
			<td>
				<a class='btn btn-primary btn-xs' onclick="if(change_input()) Dajaxice.portal.save_update(Dajax.process, {'form':$('#f1').serialize(true)})" >Save</a>
				<a onclick='cancel()' class='btn btn-danger btn-xs'>Cancel</a>
			</td>
		</tr>
		</table>
	</form>
	


templates/portal/base.html
{% load static from staticfiles %}
{% load dajaxice_templatetags %}

<!DOCTYPE html>
<html>
	<head>
		<title> {% block title %} {% endblock %} </title>
		<link rel='stylesheet' type='text/css' href = {% static 'css/bootstrap.min.css' %}>
		<link rel='stylesheet' type='text/css' href = {% static 'select2/select2.css' %}>
		<script type='text/javascript' src= {% static 'jquery-1.11.0.min.js' %} ></script>
		<script type='text/javascript' src= {% static 'jquery.dajax.core.js' %} ></script>		
		<script type='text/javascript' src= {% static 'select2/select2.js' %} ></script>
		<script type='text/javascript' src= {% static 'bootstrap/js/bootstrap.min.js' %} ></script>
		<style> {% block style %} {% endblock %} </style>
		<script> {% block script %} {% endblock %} </script>
		{% block head %} {% endblock %}
	</head>
	
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					{% block body %} {% endblock %}
				</div>
			</div>
		</div>
	</body>
<html>

templates/portal/base_new.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>Base Template</title>

    <link href="../../static/css/bootstrap.css" rel="stylesheet" />
    <link href="../../static/css/base.css" rel="stylesheet" />
  </head>

<body>

        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
          
          <a href="Home.html" class="navbar-brand">Pan-IIT Odia Community</a>
          
          <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
               <li>
                  <a href="/"><span class="glyphicon glyphicon-home"></span>  Home</a>
                </li>
                <li>
                  <a href="/forum"><span class="glyphicon glyphicon-comment"></span>  Forum</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-file"></span>  Pages<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">IIT M</a></li>
                    <li><a href="#">IIT B</a></li>
                    <li><a href="#">IIT K</a></li>
                    <li><a href="#">IIT D</a></li>
                  </ul>
                </li>
                <li>
                  <a href="#"><span class="glyphicon glyphicon-log-in"></span>  Login</a>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
   <!-- Nav tabs -->
<div class="container">
<div class="row">
 <div id="navtab" class="col-md-2">
<ul class="nav nav-pills nav-stacked">
  <li class="active"><a href="#iitmhome" data-toggle="tab">IIT Home</a></li>
  <li><a href="#people" data-toggle="tab">People</a></li>
  <li><a href="#events" data-toggle="tab">Events</a></li>
  <li><a href="#alumni" data-toggle="tab">Alumni</a></li>
</ul>
</div>
<!-- Tab panes -->
<div class="tab-content col-md-10">
  <div class="tab-pane active" id="iitmhome">
  <div class="col-md-11">
  <img src="http://static.wixstatic.com/media/9440c3_3d1128685841519625e63140259b8279.png_srz_p_200_200_75_22_0.50_1.20_0.00_png_srz" style="float:left;margin-right:20px;margin-top:20px;">
  <h2 align="center" style="margin-bottom:20px;">Welcome to Utkala Association, IITM</h2>
  <p>The Indian Institute of Technology Madras (IIT Madras) is an autonomous public engineering institution located in Chennai (formerly Madras), Tamil Nadu. It is recognized as an Institute of National Importance by the Government of India. Founded in 1959 with technical and financial assistance from the government of the former West Germany, it was the third Indian Institutes of Technology that was established by the Government of India through an Act of Parliament, to provide education and research facilities in engineering and technology.</p>
  </div>
  </div>
  <div class="tab-pane" id="people">Coming Soon...</div>
  <div class="tab-pane" id="events">Coming Soon...</div>
  <div class="tab-pane" id="alumni">Coming Soon...</div>
</div>
</div>

<div class="row">

<div class="col-md-5">
<h4 style="margin-left:10px;"><span class="glyphicon glyphicon-list-alt blue" style="margin-right:5px;"></span> UPCOMING EVENTS</h4>
<hr  />
<div class="col-md-12">
<div class="col-md-3" align="center"><h4 id="hover_happen">12 JAN</h4></div>
<div class="col-md-9">
<p><strong>TITLE</strong></p>
<p>Here , we can write about all the happenings of the event .</p>
</div>
<hr  />
</div>
<div class="col-md-12">
<div class="col-md-3" align="center"><h4 id="hover_happen">28 JAN</h4></div>
<div class="col-md-9">
<p><strong>TITLE</strong></p>
<p>Description of the event</p>
</div>
<hr  />
</div>
<div class="col-md-12">
<div class="col-md-3" align="center"><h4 id="hover_happen">3 FEB</h4></div>
<div class="col-md-9">
<p><strong>TITLE</strong></p>
<p>Description of the event</p>
</div>
<hr  />
</div>
</div>

<div class="col-md-4">
<h4 style="margin-left:10px;"><span class="glyphicon glyphicon-arrow-up blue" style="margin-right:5px;"></span> UPDATES</h4>
<hr />
<div class="col-md-12">
<p id="hover_happen"><strong>Jan 28,2014</strong></p>
<p>Here , we can write about all the happenings of the association and its people. </p>
<hr />
</div>
<div class="col-md-12">
<p id="hover_happen"><strong>Jan 30,2014</strong></p>
<p>Here , we can write about all the happenings of the association and its people. </p>
<hr />
</div>
<div class="col-md-12">
<p id="hover_happen"><strong>Feb 31,2014</strong></p>
<p>Here , we can write about all the happenings of the association and its people. </p>
<hr />
</div>
</div>

<div class="col-md-3">
<h4 style="margin-left:10px;"><span class="glyphicon glyphicon-earphone blue" style="margin-right:5px;"></span> CONTACT US</h4>
<hr  />
<div class="col-md-12">
<p style="margin-bottom:50px;">Utkala Association,IITM</p>
</div>
<h4 style="margin-left:10px;"><span class="glyphicon glyphicon-envelope blue" style="margin-right:5px;"></span> FOLLOW US</h4>
<hr />
<img src="../../static/img/icons/facebook-icon.png" width="30" height="30" class="img-rounded" style="margin-left:10px;cursor:pointer;"/>
<img src="../../static/img/icons/twitter-icon.png" width="30" height="30" class="img-rounded" style="cursor:pointer;"/>
<img src="../../static/img/icons/Web-Google-plus-alt-Metro-icon.png" width="30" height="30" class="img-rounded" style="cursor:pointer;"/>

</div>
</div>

<!-- footer-->
<footer>
 <p><a href="#contact us">Contact us</a>.<a href="#about">About</a>.</p>
</footer>
	<script src="../../static/js/jquery.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/jquery-1.10.2.js"></script>
</body>
</html>

templates/portal/dashboard.html
{% extends 'portal/base.html' %}
{% load dajaxice_templatetags %}

		{% block title %}Dashboard{% endblock %}
		
		{% block head %} 
			{% dajaxice_js_import %}
		{% endblock %}
		
		{% block style %}
			#add_event #submit {
				float:right;
				margin:5px;
				margin-top: 10px;
			}			
		{% endblock %}
		
		{% block script %}
		    $(document).ready(function(){
				Dajaxice.portal.reload(Dajax.process)
			});
			
			function change_type() {
				$('#id_date_time').prop('type', 'datetime-local');
			}
			
			function change_input() {
				value = $('#id_date_time').val();
				value = value.replace('T',' ');
				$('#id_date_time').prop('type', 'datetime');
				$('#id_date_time').val(value);
				return true;
			}
			
			function change_input_back() {
				value = $('#id_date_time').val();
				value = value.replace(' ','T');
				$('#id_date_time').prop('type', 'datetime-local');
				$('#id_date_time').val(value);
				return true;
			}
			
			function confirm_deletion() {
				if (confirm('Are you sure you want to delete this entry?')){
					return true;
				}				
				else return false;
			}
			
			function cancel() {
				$('#add_event').html('');
			}
			
			function change_editform() {
				value = $('#id_date_time').val();
				value = value.replace(' ','T');
				$('#id_date_time').prop('type', 'datetime-local');
				$('#id_date_time').val(value);
			}
			
			function change_select() {
				$('#insti').select2({placeholder:'Campus'});
				$('#type').select2({placeholder:'Category'});
			}
			
		{% endblock %}	
	{% block body %}
		<div class="col-md-9">
		<h3>EVENTS</h3>
		<div id='div_events'>
		</div>
		<button class="btn btn-primary btn-sm" onclick='Dajaxice.portal.add_event(Dajax.process)'>Add Event</button>
		
		<h3>UPDATES</h3>
		<div id='div_updates'>
		</div>
		
		<button class="btn btn-primary btn-sm" onclick='Dajaxice.portal.add_update(Dajax.process)'>Add Update</button>
		</div>
		<div id='add_event' class="col-md-3"></div>
	{% endblock %}
		
		
		
		
		
		
		
		
		

templates/portal/dashboard_new.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>Dash Board</title>

    <link href="../../static/css/bootstrap.css" rel="stylesheet" />
    <link href="../../static/css/dashboard.css" rel="stylesheet" />
  </head>

<body>
 <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
          
          <a href="Home.html" class="navbar-brand">Pan-IIT Odia Community</a>
          
          <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
               <li>
                  <a href="/"><span class="glyphicon glyphicon-home"></span>  Home</a>
                </li>
                <li>
                  <a href="/forum"><span class="glyphicon glyphicon-comment"></span>  Forum</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-file"></span>  Pages<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">IIT M</a></li>
                    <li><a href="#">IIT B</a></li>
                    <li><a href="#">IIT K</a></li>
                    <li><a href="#">IIT D</a></li>
                  </ul>
                </li>
                <li>
                  <a href="#"><span class="glyphicon glyphicon-user"></span>  Profile</a>
                </li>
                <li>
                <a href="#"><span class="glyphicon glyphicon-log-out"></span>  Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
    
    <div class="row">
    <div class="col-md-9">
    <h3>Event</h3>
    <table class="table">
    <tr>
    <td class="col-md-2">Name</td>
    <td class="col-md-4">Description</td>
    <td class="col-md-2">Date-Time</td>
    <td class="col-md-2">Location</td>
    </tr>
    </table>
    
    <h3>Updates</h3>
    <table class="table">
    <tr>
    <td class="col-md-3">Title</td>
    <td class="col-md-2">Date-Time</td>
    <td class="col-md-5">Update</td>
    </tr>
    </table>
    </div>
    </div>
     <script src="../../static/js/jquery-1.10.2.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    
    </body>
    </html>

templates/portal/div_events.html

<table class='table table-bordered table-hover' id='table_events'>
	<tr>
		<td>Event Name</td>
		<td>Description</td>
		<td>Date &amp; Time</td>
		<td>Location</td>
		<td>Options</td>
	</tr>
	{% for e in events %}
	<tr id='event{{e.id}}'>
	<td><strong> {{ e.name }} </strong></td>
	<td> {{ e.description }} </td>
	<td> {{ e.date_time }} </td>
	<td> {{ e.location }} </td>
	<td>
		<button class='btn btn-warning btn-xs' onclick="Dajaxice.portal.edit_event(Dajax.process, {'event_id': {{e.id }} })">Edit</button>
		<button class='btn btn-danger btn-xs' onclick="if(confirm_deletion()) Dajaxice.portal.delete_event(Dajax.process, {'event_id': {{ e.id }} })">Delete</button>
	</td>
	</tr>
	{% endfor %}
</table>
	

templates/portal/div_updates.html

<table class='table table-bordered table-hover' id='table_updates'>
<tr>
		<th>Title</th>
		<th>Date &amp; Time</th>
		<th>Update</th>
		<th>Options</th>
	</tr>
{% for e in updates %}
<tr id='update{{e.id}}'>
<th> {{ e.title }} </th>
<td> {{ e.date_time }} </td>
<td> {{ e.update }} </td>
<td>
	<button class='btn btn-warning btn-xs' onclick="Dajaxice.portal.edit_update(Dajax.process, {'update_id': {{e.id }} })">Edit</button>
	<button class='btn btn-danger btn-xs' onclick="if(confirm_deletion()) Dajaxice.portal.delete_update(Dajax.process, {'update_id': {{ e.id }} })">Delete</button>
</td>
</tr>
{% endfor %}
</table>
	

templates/portal/edit_event.html
{% load staticfiles %}	
 
<form id='f1' method=post >
{% csrf_token %}
	<table>
	    {{ edit_event_form.as_table }}				
	<tr>
		<th></th>
		<td>
			<a class='btn btn-primary btn-xs' onclick="if(change_input()) Dajaxice.portal.save_edited_event(Dajax.process, {'form':$('#f1').serialize(true), 'event_id' : {{ id }} })" >Save</a>
			<a onclick='cancel()' class='btn btn-danger btn-xs'>Cancel</a>
		</td>
	</tr>
	</table>
</form>
	

templates/portal/edit_update.html
{% load staticfiles %}	

<table>	
	<form id='f1' method=post class="form form-horizontal">
		{% csrf_token %}
	    {{ edit_update_form.as_table }}				
		<tr>
		<th></th>
		<td>
			<a class='btn btn-primary btn-xs' onclick="if(change_input()) Dajaxice.portal.save_edited_update(Dajax.process, {'form':$('#f1').serialize(true), 'update_id': {{ id }} })" >Save</a>
			<a onclick='cancel()' class='btn btn-danger btn-xs'>Cancel</a>
		</td>
		</tr>
	</form>
</table>

templates/portal/event.html
{% extends 'portal/base.html' %}
{% load dajaxice_templatetags %}

{% block head %}
	{% dajaxice_js_import %}
{% endblock %}
{% block title %}Events{% endblock %}
{% block script %}
    var joined = {{ joined }};
	if(joined == 1) {
		$(document).ready(function() { $('#join').hide()});
	}
	else {
		$(document).ready(function() { $('#leave').hide(); $('#number').hide()});
	}
{% endblock %}

{% block body %}
	<h1>{{ event.name }} </h1>
	<p>{{ event.description }}</p>
	<p><strong>When:</strong> {{ event.date_time }}</p>
	<p><strong>Where:</strong> {{ event.location }}	</p>
	{% if user.is_authenticated %}
	<p>
	<button id='join' class='btn btn-primary btn-xs' onclick="Dajaxice.portal.join_event(Dajax.process, {'user_id': {{ user.id }} , 'event_id': {{ event.id }} })" >Join</button>
	<button id='leave' class='btn btn-warning btn-xs' onclick="Dajaxice.portal.leave_event(Dajax.process, {'user_id': {{ user.id }} , 'event_id': {{ event.id }} })" >Leave</button>
	</p>
	{% endif %}
	<span id='number'>You and </span>{{num}} other(s) are going 
	<div id='notif' style='color:red'></div>
	
{% endblock %}

<!--Dajaxice.portal.add_user(Dajax.process, {'user_id': {{ user.id }} , 'event_id': {{ event.id }} })-->

templates/portal/homepage.html
sdjgjhsd

templates/portal/homepage_admin.html
fjhds