accounts/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.views.generic.base import TemplateView

#from accounts.views import AccountActivationView as ActivationView
from accounts.views import AccountRegistrationView as RegistrationView
from accounts.views import AccountEditView
from registration.backends.default.views import ActivationView

urlpatterns = patterns('',
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
					   
					   
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           ActivationView.as_view(),
                           name='registration_activate'),
					   
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
					   url(r'^register/X/$',
                           AccountEditView.as_view(template_name='registration/registration_form.html'),
                           name='registration_disallowed'),
                       )
					   
                       

pybbm_sample/urls.py
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pybbm_sample.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^forum/',include('pybbm_tag.urls', namespace='pybb_tag')),
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^dashboard/', 'portal.views.dashboard'),
	url(r'^home/(?P<insti>[a-z]+)/dashboard', 'portal.views.homepage_admin'),
	url(r'^home/(?P<insti>[a-z]+)/', 'portal.views.homepage'),	
    url(r'^$', 'portal.views.index'),
	url(r'^events/(?P<event_id>\d+)/','portal.views.events'),
    url(r'^dajaxice/',include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

)

urlpatterns += patterns('django.views.static', (r'^static/(?P<path>.*)$'
                        , 'serve',
                        {'document_root': settings.STATIC_ROOT,
                        'show_indexes': True}))

pybbm_tag/urls.py
from django.conf.urls import patterns, include, url
from pybbm_tag.views import AddPostViewWrapper,ForumViewWrapper, EditPostViewWrapper, TopicViewWrapper

urlpatterns = patterns('',
							url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostViewWrapper.as_view(), name='add_topic'),
							url('^forum/(?P<pk>\d+)/$', ForumViewWrapper.as_view(), name='forum'),
							url('^post/(?P<pk>\d+)/edit/$', EditPostViewWrapper.as_view(), name='edit_post'),
							url('^topic/(?P<pk>\d+)/$', TopicViewWrapper.as_view(), name='topic'),
                       )

templates/pybb/_button_new_topic.html
{% load url from future %}
{% load i18n %}<a href="{% url 'pybb:add_topic' forum.id %}" class="new-topic btn btn-primary">{% trans "New topic" %}</a>

templates/pybb/_button_submit.html
{% load i18n %}<input type="submit" class="btn btn-primary" value="{% if submit_text %}{{ submit_text }}{% else %}{% trans "Submit" %}{% endif %}" />

templates/pybb/attachments_formset.html
{% load pybb_tags %}

{% if request.user|pybb_may_attach_files %}
    {% load i18n %}
    <div class='attachments-form'>
        <a class='attachment-link' onclick='$("div.attachments-form table").toggle();return false;' href='#'>{% trans "Add attachments" %}</a>
        {{ aformset.management_form }}
            <table style='display:none;'>
            {% for form in aformset %}
                <tr>
                    <td>{{ form.id }} {{ form.file }}</td>
                    <td>{% if form.instance.pk %}{{ form.DELETE }} {% trans "delete" %}{% endif %}</td>
                </tr>
            {% endfor %}
            </table>
    </div>
{% endif %}

templates/pybb/avatar.html
{% load pybb_tags %}
{% friendly_load thumbnail %}
<div class="avatar">
    {% pybb_get_profile user=user as user_profile %}
    <a href="{{ user_profile.get_absolute_url }}">
        {% if_has_tag thumbnail %}
            {% thumbnail user_profile.avatar PYBB_AVATAR_DIMENSIONS as avatar %}
                <img src="{{ avatar.url }}" alt="{{ user }} avatar" />
            {% empty %}
                <img src="{{PYBB_DEFAULT_AVATAR_URL}}" alt="default avatar" />
            {% endthumbnail %}
        {% else %}
            {% if user_profile.avatar %}
                <img src="{{ user_profile.avatar.url }}" alt="{{ user }} avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}" />
            {% else %}
                <img src="{{PYBB_DEFAULT_AVATAR_URL}}" alt="default avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}" />
            {% endif %}
        {% endif_has_tag %}
    </a>
</div>

templates/pybb/base.html
{% extends PYBB_TEMPLATE|default:"base.html" %}
{% load staticfiles %}

{% load url from future %}

{% load i18n pybb_tags %}

{%block title %}{{ PYBB_DEFAULT_TITLE }}{% endblock title %}

{% block extra_head %}
    {{ block.super }}
    <!-- Feeds -->
    <link rel="alternate" type="application/atom+xml" href="{% url 'pybb:feed_posts' %}" title="{% trans "Latest posts on forum" %}" >
    <link rel="alternate" type="application/atom+xml" href="{% url 'pybb:feed_topics' %}" title="{% trans "Latest topics on forum" %}" >
	<link rel='stylesheet' type='text/css' href = {% static 'datatables/assets/css/datatables.css' %}>
	<script type='text/javascript' src= {% static 'datatables/assets/js/jquery.dataTables.js' %} ></script>
	<script>
      $(document).ready( function () {
          $('#forum-table').dataTable( {
              "sDom": '<"H"Tfr>t<"F">',
          } );
      } );
    </script>
{% endblock %}

{% block breadcrumb %}
    {% include "pybb/breadcrumb.html" %}
{% endblock %}

{% block content %}{% endblock content %}


templates/pybb/breadcrumb.html
{% load url from future %}
{% load i18n pybb_tags %}
    {% include "pybb/breadcrumb_top_extra_crumb.html" %}
    <li><a href="{% url 'pybb:index' %}">{% trans "Home" %}</a></li>
    {% if object %}
        {% if object.get_parents %}
            {% for obj in object.get_parents %}
                <li>{% pybb_link obj %}</li>
            {% endfor %}
        {% endif %}
        {% if extra_crumb %}
            <li>{% pybb_link object %}</li>
        {% else %}
            <li>{{ object }}</li>
        {% endif %}
    {% endif %}
    {% if extra_crumb %}
        <li>{% trans extra_crumb %}</li>
    {% endif %}

templates/pybb/delete_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags %}

{% block content %}
    <h1>{% trans "Are you sure you want to delete this message?" %}</h1>
    <div class="post-preview well">
        {{ post.body_html|safe }}
    </div>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn btn-danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock content %}

templates/pybb/edit_profile.html
{% extends 'pybb/base.html' %}

{% load url from future %}

{% load i18n pybb_tags %}

{% block title %}{% trans "Profile editing" %}{% endblock title %}

{% block content %}
    <h2>{% trans "Profile editing" %}</h2>
    {% include 'pybb/avatar.html' with user=user %}
    <form method="post" enctype="multipart/form-data" class="form form-horizontal profile-edit">
        {% csrf_token %}
        <fieldset>
            <legend>{% trans "Profile editing" %}</legend>
            {% include "pybb/form.html" %}
            <p>{% include "pybb/_button_save.html" %}</p>
        </fieldset>
    </form>
    <h2>{% trans "Subscriptions on topics" %}</h2>
    <ul>
        {% for sub in user.subscriptions.all %}
            <li>
                {% pybb_link sub %}
                &mdash;
                <strong>
                    <a href="{% url 'pybb:delete_subscription' sub.id %}">{% trans "delete" %}</a>
                </strong>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/pybb/form_field.html
{% load pybb_tags %}

<div class="form-group {% if field.is_required %}required{% endif %} {% if field.errors %}error{% endif %}">
    {% if not hide_labels or hide_labels == 0 %}
        <label class="" for="{{ field.auto_id }}">
            {{ field.field.label }}
        </label>
    {% endif %}
    <div class="">
        {{ field }}
        {% for error in field.errors %}
            <span class="field-errors alert alert-error">{{ field.errors }}</span>
        {% endfor %}
    </div>
</div>

templates/pybb/forum.html
{% extends 'pybb/base.html' %}
{% load pybb_tags i18n %}

{% block title %}{{ forum.name }}{% endblock title %}

{% block breadcrumb %}
    {% with forum as object %}
        {% include "pybb/breadcrumb.html" %}
    {% endwith %}
{% endblock %}

{% block content %}
    <div class="forum">
        <h1>{{ forum.name }}</h1>
        {% if forum.headline %}
            <div class="forum-headline alert alert-block">
                {{ forum.headline|safe }}
            </div>
        {% endif %}

        {% include "pybb/pagination.html" %}

        {% include 'pybb/forum_list.html' with forum_list=forum.forums_accessed category='' parent_forum=forum %}

        {% include "pybb/topic_list.html" %}

        {% include "pybb/pagination.html" %}

        {% pybb_get_profile user=user as user_profile %}

        {% if PYBB_ENABLE_ANONYMOUS_POST or not user_profile.is_banned %}
            <div class="controls">
                {% include "pybb/_button_new_topic.html" %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/pybb/forum_last_update_info.html
{% if forum.updated %}
    {{ forum.updated|date:"d.m.Y H:i" }}
{% endif %}

templates/pybb/index.html
{% extends 'pybb/base.html' %}

{% load url from future %}

{% load i18n %}

{% block title %}{{ PYBB_DEFAULT_TITLE }}{% endblock title %}

{% block breadcrumb %}
    {% with extra_crumb="Forum" %}{% include "pybb/breadcrumb.html" %}{% endwith %}
{% endblock %}

{% block content %}
    {% if categories %}
        {% for category in categories %}
            {% include 'pybb/category.html' %}
        {% endfor %}
    {% else %}
        <h2>{% trans "Forum categories are not created" %}</h2>
        <a href="{% url 'admin:pybb_category_add' %}">{% trans "Add a category now" %}</a>
    {% endif %}
    {% if user.is_authenticated %}
        <div id='mark-all-as-read'>
            <a href='{% url 'pybb:topic_latest' %}'>
                {% trans "Last updates in topics" %}
            </a>
		&nbsp;&nbsp;
            <a href='{% url 'pybb:mark_all_as_read' %}'>
                {% trans "Mark all forums as read" %}
            </a>
        </div>
    {% endif %}
{% endblock content %}

templates/pybb/poll_edit_form.html
{% load i18n %}
{% include "pybb/form_field.html" with field=form.poll_type %}
<div id="poll-question">
  {% include "pybb/form_field.html" with field=form.poll_question %}
</div>
<div id="poll-answers-formset" style="display: none;">
  <br>{% trans 'Poll answers' %}
    {% include "pybb/form_errors.html" with form=pollformset %}
    {% for form_answer in pollformset %}
        <div class="poll-answer-form">
            {% include "pybb/form.html" with form=form_answer hide_labels=1 %}
        </div>
    {% endfor %}
  {{ pollformset.management_form }}
</div>

<script type="text/javascript">
  window.onload = function () {
    $('div#poll-answers-formset div.poll-answer-form').formset({
      deleteText:'{% trans 'remove answer' %}',
      addText:'{% trans 'add answer' %}',
      prefix: 'poll_answers'
    });

    var toggle_poll_answers_formset = function (poll_type) {
      if (poll_type === "0") {
        $('div#poll-answers-formset').hide();
        $('div#poll-question').hide();
      } else {
        $('div#poll-answers-formset').show();
        $('div#poll-question').show();
      }
    };

    $('#id_poll_type').each(function () {
      toggle_poll_answers_formset($(this).val());
    }).change(function () {
      toggle_poll_answers_formset($(this).val());
    });
  };
</script>

templates/pybb/post_template.html
{% load url from future %}
{% load i18n pybb_tags %}
{% load query %}
{% pybb_get_profile user=post.user as post_user_profile %}
{% pybb_get_profile user=user as user_profile %}

<a name="post-{{ post.id }}"></a> {# may be remove this string? #}
<table class="table table-bordered post {% if post.on_moderation %}on-moderation{% endif %}" id="post-{{ post.id }}">
    <thead class="post-header">
    <tr>
    <th colspan="2">
        <a class="permalink" href="{{ post.get_absolute_url }}">#</a>
        <span class="updated">{% pybb_time post.created %}</span>
    </th>
    </tr>
    </thead>
    <tbody>
    <tr class="post-row">
        <td class="col-md-3 post-info">
            {% include "pybb/avatar.html" with user=post.user %}

            <div class="post-author"><a href="{{ post_user_profile.get_absolute_url }}"><span class="post-username">{{ post.user.username }}</span></a></div>
            {% if post_user_profile.rank %}
                <div class='rank'>
                    {% trans "Rank" %}: {{ post_user_profile.rank }}
                    {% if user.is_authenticated and user != post.user %}
                        <a href='#' class='vote' rel='{{ post_user_profile.get_vote_up_url }}'>+</a>
                        <a href='#' class='vote' rel='{{ post_user_profile.get_vote_down_url }}'>-</a>
                    {% endif %}
                </div>
            {% endif %}
            {% if user.is_superuser %}
                <div class="post-extra-info">{{ post.user_ip }}</div>
            {% endif %}

            <div class="post-controls">
                {% if user.is_moderator or post|pybb_posted_by:user %}
                    <a href="{% url 'pybb:edit_post' pk=post.id %}">{% trans "Edit" %}</a>
                {% endif %}
                {% if user.is_moderator %}
                    <a onclick="pybb_delete_post('{% url 'pybb:delete_post' post.id %}',
                            'post-{{ post.id }}', '{% trans 'Delete post?' %}'); return false;"
                       href="{% url 'pybb:delete_post' post.id %}">{% trans "Delete" %}</a>
                    {% if post.on_moderation %}
                        <a href="{% url 'pybb:moderate_post' pk=post.id %}">{% trans "Approve post" %}</a>
                    {% endif %}
                {% endif %}

                {% if perms.pybb.change_post and user.is_staff %}
                    <a href="{% url 'admin:pybb_post_change' post.id %}">{% trans 'Admin' %}</a>
                {% endif %}

            </div>
        </td>
        <td class="col-md-9 post-content">
            {{ post.body_html|safe }}

            {% if not user.is_authenticated or user_profile.show_signatures %}
                {% if post_user_profile.signature %}
                    <div class="post-signature">
                        {{ post_user_profile.signature_html|safe }}
                    </div>
                {% endif %}
            {% endif %}
            {% if post.updated %}
                <div class="updated-message">{% trans "Edited" %} {% pybb_time post.updated %}</div>
            {% endif %}
			
            {% comment %}
                    {% if post.attachment_cache %}
                    {% for attach in post.attachment_cache %}
                    <br/>
                    {% trans "Attachment" %}: <a href="{{ attach.get_absolute_url }}">{{ attach.name }}</a> ({{ attach.size_display }})
                    {% endfor %}
                    {% endif %}
            {% endcomment %}
            <div class="post-related">
                <a href="{% url 'pybb:add_post' topic.id %}?quote_id={{ post.id }}" class="quote-link">{% trans "quote" %}</a>
                <a href="#" class="quote-selected-link">{% trans "quote selected" %}</a>
                <div class='attachments'>
                    {% for attachment in post.attachments.all %}
                        <a href="{{ attachment.file.url }}"><img src="{{ STATIC_URL }}pybb/img/attachment.png"> {{ attachment.size_display }}</a>
                    {% endfor %}
                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>